spring:
  application:
    name: msvc_ficohsa_insurance

  datasource:
    url: jdbc:postgresql://localhost:5439/insurance_db
    username: ficohsa-seguros
    password: ficohsa_seguros!10

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ficohsa
        format_sql: true
    show-sql: true

server:
  port: 8080

security:
  jwt:
    secret: fmC/WmOkdANkLoAy9erEsYs+B0hKejvJ2K1pGjMQ198=
    expiration: 3600000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    displayRequestDuration: true
